// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMXc8--LRPdONdhwWSmrG0uzYWv3P_hMI',
    appId: '1:92131158265:web:e277bef2e094e2741d5a28',
    messagingSenderId: '92131158265',
    projectId: 'flutterpks-be354',
    authDomain: 'flutterpks-be354.firebaseapp.com',
    storageBucket: 'flutterpks-be354.firebasestorage.app',
    measurementId: 'G-95NX1720HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSl1TZbtAnGFXd8CG2oB_tY4DF0B4Jjk',
    appId: '1:92131158265:android:2584ccae757830171d5a28',
    messagingSenderId: '92131158265',
    projectId: 'flutterpks-be354',
    storageBucket: 'flutterpks-be354.firebasestorage.app',
  );
}
